### ISSUE TITLE
execute seed do not follow the order in catalog file

### ISSUE THREAD

**Issue by SmileZero** [sue445/heart_seed#20]
when I use catalog to execute seed in my app.
It can not follow the order of tables what I write in catalog settings.

And it caused some validate errors when my model validate the data exits in other tables that have not seed yet.

I suggest heart_seed provide a way to follow the order in catalog file 
or provide some config way to avoid validations

thank you.

**Comment by sue445** [comment]
Hmm
I'll do!

**Comment by sue445** [comment]
@SmileZero I released `v0.0.5` (including #22 , #23 , #24)
https://github.com/sue445/heart_seed/blob/master/CHANGELOG.md#005-20150209

**Comment by SmileZero** [comment]
:+1: 
Awesome!
